version: "3.0"
services:
    application:
        image: php:${PHP_VERSION}
        environment:
            - API_KEY
        volumes:
            -
                type: bind
                source: ..
                target: /application
        working_dir: /application
